### ISSUE TITLE
[P0] Configure job publish pypi for Open Data Hub

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit-tgis-backend#1]

**Comment by heyselbi** [comment]
@Xaenalt could you provide more details here? and add necessary labels, complexity etc?

**Comment by Xaenalt** [comment]
Progress of it depends on some additional development from IBM, for now we are working around it by using pipfile to make repeatable builds using the git link

**Comment by Xaenalt** [comment]
This one requires IBM to determine a release to publish to pypi, this is out of our control in general, but we do have the aforementioned workaround.
